apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chain-sync-watch.configMapName" . }}
  labels:
    {{- include "chain-sync-watch.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
