{{- if .Values.worker.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chain-sync-watch.fullname" . }}-worker
  labels:
    {{- include "chain-sync-watch.componentLabels" (merge (dict "component" "worker") .) | nindent 4 }}
spec:
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chain-sync-watch.componentSelectorLabels" (merge (dict "component" "worker") .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chain-sync-watch.componentSelectorLabels" (merge (dict "component" "worker") .) | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.worker.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "chain-sync-watch.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      terminationGracePeriodSeconds: {{ .Values.worker.terminationGracePeriodSeconds }}
      containers:
        - name: csw-worker
          image: {{ include "chain-sync-watch.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          command: ["csw-worker"]
          envFrom:
            - configMapRef:
                name: {{ include "chain-sync-watch.configMapName" . }}
            - secretRef:
                name: {{ include "chain-sync-watch.secretName" . }}
          ports:
            - name: health
              containerPort: {{ .Values.worker.healthPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.worker.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.worker.readinessProbe | nindent 12 }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep {{ .Values.worker.preStopSleepSeconds }}"]
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
