/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List supported chain catalog entries */
        get: operations["list-chains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List discrepancies with optional filters */
        get: operations["list-diffs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diffs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a discrepancy record by id */
        get: operations["get-diff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diffs/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-verify a discrepancy against the original sources */
        post: operations["replay-diff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 whenever the server process is accepting HTTP traffic. Does not probe downstream dependencies.
         */
        get: operations["health-live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 when Postgres and Redis are reachable; 503 otherwise.
         */
        get: operations["health-ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List runs with optional filters */
        get: operations["list-runs"];
        put?: never;
        /** Create and dispatch a verification run */
        post: operations["create-run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a run by id */
        get: operations["get-run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a pending or running run */
        post: operations["cancel-run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/runs/{id}/diffs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List discrepancies produced by a specific run */
        get: operations["get-run-diffs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active schedules */
        get: operations["list-schedules"];
        put?: never;
        /** Register a recurring verification schedule */
        post: operations["create-schedule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedules/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deactivate a recurring schedule */
        delete: operations["cancel-schedule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List configured source adapter rows for a chain */
        get: operations["list-sources"];
        put?: never;
        /** Create a new source configuration */
        post: operations["create-source"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List adapter type strings registered in this binary */
        get: operations["list-source-types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a source configuration by id */
        get: operations["get-source"];
        /** Update a source configuration */
        put: operations["update-source"];
        post?: never;
        /** Delete a source configuration */
        delete: operations["delete-source"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources/{id}/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inspect a source's capability matrix at runtime */
        get: operations["get-source-capabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AddressPlanInput: {
            /** @enum {string} */
            kind: "known" | "top_n" | "random" | "recently_active";
            known?: components["schemas"]["KnownAddressesIn"];
            random?: components["schemas"]["RandomAddressesIn"];
            recently_active?: components["schemas"]["RecentlyActiveIn"];
            top_n?: components["schemas"]["TopNHoldersIn"];
        };
        CapabilityView: {
            name: string;
            /** @enum {string} */
            tier: "A" | "B" | "C" | "unknown";
        };
        ChainView: {
            /** @example Optimism */
            display_name: string;
            /**
             * Format: int64
             * @example 10
             */
            id: number;
            /** @example optimism */
            slug: string;
        };
        CreateRunRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateRunRequest.json
             */
            readonly $schema?: string;
            address_plans?: components["schemas"]["AddressPlanInput"][] | null;
            /**
             * Format: int64
             * @example 10
             */
            chain_id: number;
            /** @description Built-in metric keys, e.g. block.hash */
            metrics: string[] | null;
            sampling: components["schemas"]["SamplingInput"];
            /** @description Required when trigger.kind is scheduled */
            schedule?: components["schemas"]["ScheduleInput"];
            token_plans?: components["schemas"]["TokenPlanInput"][] | null;
            trigger: components["schemas"]["TriggerInput"];
        };
        CreateRunResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateRunResponse.json
             */
            readonly $schema?: string;
            /** @description Populated only for scheduled triggers */
            job_id?: string;
            run_id: string;
        };
        CreateScheduleRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateScheduleRequest.json
             */
            readonly $schema?: string;
            address_plans?: components["schemas"]["AddressPlanInput"][] | null;
            /**
             * Format: int64
             * @example 10
             */
            chain_id: number;
            metrics: string[] | null;
            sampling: components["schemas"]["SamplingInput"];
            /** @description Cron + timezone */
            schedule: components["schemas"]["ScheduleInput"];
            token_plans?: components["schemas"]["TokenPlanInput"][] | null;
        };
        CreateScheduleResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateScheduleResponse.json
             */
            readonly $schema?: string;
            /** @description Opaque identifier for DELETE /schedules/{id} */
            job_id: string;
            /** @description First Run the schedule materialised; absent for deferred modes */
            run_id: string;
        };
        CreateSourceRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateSourceRequest.json
             */
            readonly $schema?: string;
            /** @description Plaintext secret; server encrypts with CSW_SECRET_KEY before persisting. Empty = no credential. */
            api_key?: string;
            /**
             * Format: int64
             * @example 10
             */
            chain_id: number;
            /** @description Defaults to true when omitted */
            enabled?: boolean;
            endpoint: string;
            options?: {
                [key: string]: unknown;
            };
            /** @description Adapter type registered in the gateway (rpc / blockscout / routescan by default; private builds may add more) */
            type: string;
        };
        DiffView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/DiffView.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Run's verification anchor
             */
            anchor_block: number;
            /** Format: int64 */
            block: number;
            /** Format: date-time */
            detected_at: string;
            id: string;
            metric_category: string;
            metric_key: string;
            resolved: boolean;
            /** Format: date-time */
            resolved_at?: string;
            run_id: string;
            /**
             * Format: int64
             * @description Sampling seed for Tier B reproducibility
             */
            sampling_seed?: number;
            severity: string;
            subject: components["schemas"]["SubjectView"];
            /**
             * @description Metric tier at save time
             * @enum {string}
             */
            tier: "A" | "B" | "C" | "unknown";
            trusted_sources: string[] | null;
            values: components["schemas"]["ValueSnapshotView"][] | null;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FixedListIn: {
            /** @description Block heights to verify */
            numbers: number[] | null;
        };
        HealthResponseBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/HealthResponseBody.json
             */
            readonly $schema?: string;
            detail?: string;
            /** @example ok */
            status: string;
        };
        KnownAddressesIn: {
            /** @description 0x-prefixed EIP-55 addresses */
            addresses: string[] | null;
        };
        KnownTokensIn: {
            /** @description 0x-prefixed EIP-55 ERC-20 contract addresses */
            tokens: string[] | null;
        };
        LatestNIn: {
            /**
             * Format: int64
             * @description How many trailing blocks from tip
             */
            n: number;
        };
        ListChainsResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListChainsResponse.json
             */
            readonly $schema?: string;
            items: components["schemas"]["ChainView"][] | null;
            /** Format: int64 */
            total: number;
        };
        ListDiffsResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListDiffsResponse.json
             */
            readonly $schema?: string;
            items: components["schemas"]["DiffView"][] | null;
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /** Format: int64 */
            total: number;
        };
        ListRunsResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListRunsResponse.json
             */
            readonly $schema?: string;
            items: components["schemas"]["RunView"][] | null;
            /** Format: int64 */
            limit: number;
            /** Format: int64 */
            offset: number;
            /**
             * Format: int64
             * @description Total rows matching the filter (not just this page)
             */
            total: number;
        };
        ListSchedulesResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListSchedulesResponse.json
             */
            readonly $schema?: string;
            items: components["schemas"]["ScheduleView"][] | null;
            /** Format: int64 */
            total: number;
        };
        ListSourcesResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListSourcesResponse.json
             */
            readonly $schema?: string;
            items: components["schemas"]["SourceConfigView"][] | null;
            /** Format: int64 */
            total: number;
        };
        RandomAddressesIn: {
            /** Format: int64 */
            count: number;
            /** Format: int64 */
            seed: number;
        };
        RandomIn: {
            /** Format: int64 */
            count: number;
            /**
             * Format: int64
             * @description Inclusive range end
             */
            end: number;
            /** Format: int64 */
            seed: number;
            /**
             * Format: int64
             * @description Inclusive range start
             */
            start: number;
        };
        RecentlyActiveIn: {
            /** Format: int64 */
            count: number;
            /** Format: int64 */
            recent_blocks: number;
            /** Format: int64 */
            seed: number;
        };
        ReplayDiffResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ReplayDiffResponse.json
             */
            readonly $schema?: string;
            /** @description Populated only when sources still disagree */
            new_diff_id?: string;
            original_diff_id: string;
            resolved: boolean;
        };
        RunSummaryIn: {
            /**
             * Format: int64
             * @description Tip resolved at run start; nil for Snapshot-only runs
             */
            anchor_block?: number;
            /**
             * Format: int64
             * @description Total (subject × metric) comparisons attempted
             */
            comparisons_count: number;
            sources_used: string[] | null;
            subjects: components["schemas"]["SubjectOut"][] | null;
        };
        RunView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/RunView.json
             */
            readonly $schema?: string;
            address_plan_kinds?: string[] | null;
            /** Format: int64 */
            chain_id: number;
            /** Format: date-time */
            created_at: string;
            error_message?: string;
            /** Format: date-time */
            finished_at?: string;
            id: string;
            metrics: string[] | null;
            /** Format: date-time */
            started_at?: string;
            status: string;
            strategy_kind: string;
            /** @description What the run actually compared; absent for runs that never executed */
            summary?: components["schemas"]["RunSummaryIn"];
            token_plan_kinds?: string[] | null;
            trigger_kind: string;
        };
        SamplingInput: {
            fixed_list?: components["schemas"]["FixedListIn"];
            /**
             * @description Sampling strategy discriminator
             * @example latest_n
             * @enum {string}
             */
            kind: "fixed_list" | "latest_n" | "random" | "sparse_steps";
            latest_n?: components["schemas"]["LatestNIn"];
            random?: components["schemas"]["RandomIn"];
            sparse_steps?: components["schemas"]["SparseStepsIn"];
        };
        ScheduleInput: {
            /**
             * @description Cron expression for scheduled runs
             * @example 0 *\/5 * * * *
             */
            cron_expr: string;
            /**
             * @description IANA timezone; empty defaults to UTC
             * @example UTC
             */
            timezone?: string;
        };
        ScheduleView: {
            active: boolean;
            address_plan_kinds?: string[] | null;
            /** Format: int64 */
            chain_id: number;
            /** Format: date-time */
            created_at: string;
            cron_expr: string;
            job_id: string;
            metric_keys: string[] | null;
            strategy_kind: string;
            timezone?: string;
            token_plan_kinds?: string[] | null;
        };
        SourceCapabilityMatrix: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SourceCapabilityMatrix.json
             */
            readonly $schema?: string;
            capabilities: components["schemas"]["CapabilityView"][] | null;
            /** Format: int64 */
            chain_id: number;
            id: string;
        };
        SourceConfigView: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SourceConfigView.json
             */
            readonly $schema?: string;
            /** Format: int64 */
            chain_id: number;
            /** Format: date-time */
            created_at: string;
            enabled: boolean;
            endpoint: string;
            has_secret: boolean;
            id: string;
            options: {
                [key: string]: unknown;
            };
            /** @description Adapter type (rpc / blockscout / routescan, or a private-build custom type) */
            type: string;
            /** Format: date-time */
            updated_at: string;
        };
        SourceTypesResponse: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/SourceTypesResponse.json
             */
            readonly $schema?: string;
            types: string[] | null;
        };
        SparseStepsIn: {
            /**
             * Format: int64
             * @description Inclusive range end
             */
            end: number;
            /**
             * Format: int64
             * @description Inclusive range start
             */
            start: number;
            /** Format: int64 */
            step: number;
        };
        SubjectOut: {
            a?: string;
            /** Format: int64 */
            b?: number;
            /** @enum {string} */
            k: "block" | "address_latest" | "address_at_block" | "erc20_balance" | "erc20_holdings" | "snapshot";
            /** @description Snapshot metric key (snapshot kind only) */
            n?: string;
            t?: string;
        };
        SubjectView: {
            /** @description EIP-55 address when type is address/contract */
            address?: string;
            /** @enum {string} */
            type: "block" | "address" | "contract" | "chain";
        };
        TokenPlanInput: {
            /** @enum {string} */
            kind: "known_tokens";
            known?: components["schemas"]["KnownTokensIn"];
        };
        TopNHoldersIn: {
            /** Format: int64 */
            n: number;
        };
        TriggerInput: {
            /** @description Cron expression for scheduled triggers */
            cron_expr?: string;
            /**
             * @example manual
             * @enum {string}
             */
            kind: "manual" | "scheduled" | "realtime";
            /** Format: int64 */
            realtime_block?: number;
            /** @description Operator identifier for manual triggers */
            user?: string;
        };
        UpdateSourceRequest: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateSourceRequest.json
             */
            readonly $schema?: string;
            /** @description Nil keeps existing secret; empty string still keeps; set ClearSecret=true to remove. */
            api_key?: string;
            clear_secret?: boolean;
            enabled?: boolean;
            endpoint?: string;
            options?: {
                [key: string]: unknown;
            };
        };
        ValueSnapshotView: {
            /** Format: date-time */
            fetched_at: string;
            raw: string;
            /**
             * Format: int64
             * @description Block height this observation reflects, when the source exposes it
             */
            reflected_block?: number;
            source_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListChainsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-diffs": {
        parameters: {
            query?: {
                /** @description Filter by run id */
                run_id?: string;
                /** @description Filter by metric key (e.g. block.hash) */
                metric_key?: string;
                /** @description Filter by severity (info|warning|critical) */
                severity?: string;
                /** @description Filter by resolution state ('true' or 'false') */
                resolved?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDiffsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-diff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "replay-diff": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplayDiffResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "health-live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "health-ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-runs": {
        parameters: {
            query?: {
                /** @description Filter by chain id; 0 means no filter */
                chain_id?: number;
                /** @description Filter by status (pending/running/completed/failed/cancelled) */
                status?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListRunsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateRunResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Run identifier */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cancel-run": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-run-diffs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListDiffsResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-schedules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSchedulesResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateScheduleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateScheduleResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "cancel-schedule": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-sources": {
        parameters: {
            query: {
                /** @description Target chain id */
                chain_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListSourcesResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSourceRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceConfigView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-source-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceTypesResponse"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceConfigView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSourceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceConfigView"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-source": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-source-capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceCapabilityMatrix"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
